### ISSUE TITLE
Webpack is throwing error. 

### ISSUE THREAD

**Issue by helloiamsrv** [northernv/mastering-mean#5]
Hello. I just started to learn about mean by following this course. I am getting following error whenever I am trying to start my webpack dev server 

ERROR in ./src/app.js
Module build failed: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.extname (path.js:887:5)
    at processText (C:\meanStackWorkspace\mastering-mean-master\frontend\node_modules\eslint\lib\cli-engine.js:144:30)
    at CLIEngine.executeOnText (C:\meanStackWorkspace\mastering-mean-master\frontend\node_modules\eslint\lib\cli-engine.js:671:26)
    at Linter.lintText (C:\meanStackWorkspace\mastering-mean-master\frontend\node_modules\standard-engine\index.js:65:59)
    at Object.standardLoader (C:\meanStackWorkspace\mastering-mean-master\frontend\node_modules\standard-loader\index.js:19:12)
 @ multi app

Please help so that I can understand where I am going wrong!

**Comment by shanestillwell** [comment]
@helloiamsrv from the error message, it doesn't like the `standard-loader`.

Go to the `webpack.config.js` file and remove these lines.
https://github.com/northernv/mastering-mean/blob/master/frontend/webpack.config.js#L55-L62

They are just code linting and will not affect how your app runs.
